### ISSUE TITLE
$emit closeModal breaks all scripts on page

### ISSUE THREAD

**Issue by snapey** [wire-elements/modal#106]
I have a working modal.  It opens and closes on escape or click away.

I have added a Cancel button, with the suggested `wire:click="$emit('closeModal')"`

On clicking the button, the console shows errors and all livewire components on the page are broken

Uncaught (in promise) {isFromCancelledTransition: true}  x2

Uncaught(in promise) TypeError: l is not a function x2

These two errors relate to alpine package loaded from https://unpkg.com/alpinejs@3.5.0/dist/cdn.min.js

Alpine: 3.5.0

Laravel 8.69.0

Livewire v2.7.2

Wire Elements Modal 1.0.3

**Comment by PhiloNL** [comment]
Hi @snapey 
I'm using the identical versions of Alpine, Laravel, Livewire, and the Wire Elements Modal package, and I'm unable to replicate this issue. So I expect something else may be causing the problem. To verify, I would suggest creating a fresh Laravel install with just the dependencies above and checking if the error persists. If you don't get any error, something else seems to be interfering.

**Comment by snapey** [comment]
Resolved.

I had recently installed Power-Components/livewire-powergrid and it was also installing Alpine, so I had two copies active, one in the app.js (originated from breeze) and the CDN version being pulled in by powergrid.

Sorry to clutter your issues!

**Comment by muhammedshiffin** [comment]
@snapey 
Am facing a similar issue on the TALL Stack application with Livewire PowerGrid, my modal doesn't even close on ESC or Click-Away.
Anything I am missing? I disabled the js_framework from config.

**Comment by muhammedshiffin** [comment]
> @snapey Am facing a similar issue on the TALL Stack application with Livewire PowerGrid, my modal doesn't even close on ESC or Click-Away. Anything I am missing? I disabled the js_framework from config.

Resolved.

Haven't realized the Tall Stack preset was on alpine 2.7, upgraded alpine to the latest, and it's working fine.
Thanks
