### ISSUE TITLE
dd() didnt work on modal

### ISSUE THREAD

**Issue by hai-shift** [wire-elements/modal#110]
hi
 inside the model
in blade or in the php file
the dd() didnt work and return blank page

**Comment by PhiloNL** [comment]
Hi. That's correct, you get a blank page because the modal is still hidden. If you inspect the page you can find the contents.

**Comment by hai-shift** [comment]
u can help me how to do the dd()
with example id u can

thanks :)

**Comment by PhiloNL** [comment]
Use your browser inspector to inspect the blank page. Next, look for the hidden div that contains the contents of the dd. Once you've found that div, you can remove any CSS properties which are hiding the contents. Once you've done this, the contents should be visible.
