### ISSUE TITLE
Using Open Modal with powerGrid

### ISSUE THREAD

**Issue by abbasmashaddy72** [wire-elements/modal#114]
Trows this error:

[App\Http\Livewire\DeleteModal] does not implement [LivewireUI\Modal\Contracts\ModalComponent] interface.

When checked, the CSS and JS files were not published 

using with PHP 8

**Comment by PhiloNL** [comment]
Make sure DeleteModal extends the ModalComponent class.

**Comment by abbasmashaddy72** [comment]
Okay Thanks I got your point, I will check it out

**Comment by abbasmashaddy72** [comment]
I got  it fixed by implementing the ModalComponent in DeleteModal livewire controller, but unfortunately I am getting this error now

Method App\Http\Livewire\DeleteModal::closeModalOnClickAway does not exist.

**Comment by PhiloNL** [comment]
Are you sure you are **extending** instead of **implementing**? You need to extend the base class.

```php

<?php

namespace App\Http\Livewire;

use LivewireUI\Modal\ModalComponent;

class HelloWorld extends ModalComponent
{
    public function render()
    {
        return view('livewire.hello-world');
    }
}
```

**Comment by abbasmashaddy72** [comment]
Now the error is

`Symfony\Component\ErrorHandler\Error\FatalError
Class App\Http\Livewire\DeleteDoctor cannot extend from interface LivewireUI\Modal\Contracts\ModalComponent`

`<?php

namespace App\Http\Livewire;

use Livewire\Component;
use LivewireUI\Modal\Contracts\ModalComponent;

class DeleteDoctor extends ModalComponent
{
    public function render()
    {

        return view('livewire.delete-doctor');
    }
}
`

![Screenshot from 2021-11-16 15-34-20](https://user-images.githubusercontent.com/55267488/141965005-3f9b69b7-59d5-4532-83cb-ae971448604c.png)

**Comment by PhiloNL** [comment]
Extend `use LivewireUI\Modal\ModalComponent;` not the contract

**Comment by abbasmashaddy72** [comment]
used use LivewireUI\Modal\Contracts\ModalComponent; in second one

**Comment by abbasmashaddy72** [comment]
Okay Got your Point

**Comment by abbasmashaddy72** [comment]
Thanks for the help.

That was great.
@PhiloNL
