### ISSUE TITLE
Feature request wire:click="$emit('forceCloseModal')"

### ISSUE THREAD

**Issue by boonstoppel** [wire-elements/modal#118]
I am currently only seeing closeModal as browser action:
`<button wire:click="$emit('closeModal')">No, do not delete</button>`

It would be nice to also have:
`<button wire:click="$emit('forceCloseModal')">Close window</button>`

that would trigger:
`$this->forceClose()->closeModal();`

**Comment by PhiloNL** [comment]
`$emit('closeModal', true)` should do the trick 😄

**Comment by boonstoppel** [comment]
@PhiloNL are there any plans for better documentation?
