### ISSUE TITLE
After upgrading Tailwind to V3.0 (Modal not rendering)

### ISSUE THREAD

**Issue by phaiderh** [wire-elements/modal#128]
Hello,

Modal is not rendering after upgrading Tailwind V3.0.5.

Any quick solution?

Thanks,

**Comment by PhiloNL** [comment]
Hi @phaiderh
I'm unable to reproduce this issue.
If you can share a repository with a fresh install of Laravel and Tailwind where the issue is reproduced I can take a further look.
