### ISSUE TITLE
Component didn't show

### ISSUE THREAD

**Issue by Slamet24** [wire-elements/modal#133]
I am using powergrid with wire element modal. i follow the documentation. it's fine, until i try to click button to show modal it's just show a gray transparent in the screen and the content didn't show.

**here's my content**
![Screenshot from 2021-12-25 19-23-43](https://user-images.githubusercontent.com/44310733/147384789-a4df78ed-4dc9-4413-8d8a-679a75c96389.png)

**here's the output**
![Screenshot from 2021-12-25 19-23-48](https://user-images.githubusercontent.com/44310733/147384794-0a8bb5af-9a1c-4949-ba9f-f7e47ca7efaf.png)

**Comment by kevinparchi** [comment]
@Slamet24 what was your solution to this? I'm facing the same issue
