### ISSUE TITLE
Not working with TailwindCss 3?

### ISSUE THREAD

**Issue by elfeffe** [wire-elements/modal#146]
It seems like this is not working anymore after the upgrade to TW 3

**Comment by elfeffe** [comment]
It seems like the problem is:

`            <span class="hidden sm:inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
`

The sm: before inline-block
If I do

`            <span class="hidden inline-block sm:align-middle sm:h-screen" aria-hidden="true">&#8203;</span>
`

It works. it seems to be related to my Tailwind upgrade, but anyone has any idea about how to fix it?
I also discovered that the width of the modals doesn't work, it uses the sm: modification too.

**Comment by elfeffe** [comment]
The problem is the JIT, you have to add sm to your safelist

safelist: [
        {
            pattern: /./,
            variants: ['hover','focus','sm','md'],
        },
    ],

**Comment by PhiloNL** [comment]
That is correct 😄  see the readme about whitelisting dynamic classes. If you want to support all widths, add the following:

```
    options: {
        safelist: [
            "sm:max-w-sm",
            "sm:max-w-md",
            "sm:max-w-lg",
            "sm:max-w-xl",
            "sm:max-w-2xl",
            "sm:max-w-3xl",
            "sm:max-w-4xl",
            "sm:max-w-5xl",
            "sm:max-w-6xl",
            "sm:max-w-7xl"
        ]
    },
```
