### ISSUE TITLE
Problem with alpine 3.9.1

### ISSUE THREAD

**Issue by skalero01** [wire-elements/modal#194]
Hi, had problems with the modals after alpine released the new version 3.9.1, not sure if the error its caused by an error of them, or if its an error on this package. 

Basically the error its that the first time the modal its opened it worked correctly, but if you hided and click again it started failing and showing only an empty popup.

Fixed the problem just changing to alpine 3.9.0

Send this just for inform you. Regards

**Comment by PhiloNL** [comment]
Already fixed (https://github.com/wire-elements/modal/issues/192, https://github.com/wire-elements/modal/discussions/191)
