### ISSUE TITLE
Stop rendering between save and close modal?

### ISSUE THREAD

**Issue by seabasss** [wire-elements/modal#196]
Maybe a basic question and more about livewire than the modal…

I open a modal and let’s say I have a title at the top with my current title. Below I have a title input where you can change the title with defer on it. Once I press save and the modal closes, the new title appears at the top of the modal because it’s faster than the close action. Is there anything I can put between my save action and modal close action in the livewire component that will make the view not re-render? I know I can put wire:ignore on the title, but in some scenarios I don’t want to do that. To be clear, I want the old title to stay at the top without wire:ignore or saving into a new variable.

Thanks!

**Comment by rahmanramsi** [comment]
Livewire have skipRender() function to not render html. use it on your save function, maybe it will work as you expect

**Comment by seabasss** [comment]
> Livewire have skipRender() function to not render html. use it on your save function, maybe it will work as you expect

That’s cool! Will give it a try. Thanks!
