### ISSUE TITLE
"Cannot assign int to property" when passing in data

### ISSUE THREAD

**Issue by jamesblackwell** [wire-elements/modal#197]
I am getting the error "Cannot assign int to property" when trying to open a modal from a non-livewire component. Generated code: 

```
Livewire.emit("openModal", "my-modal-test", {"user":581});
```
The modal opens fine without any data. 

Is Laravel 9 + PHP 8.1 supported?

**Comment by jamesblackwell** [comment]
Interestingly, it seems to work when this line is commented out: 

```
public User $user;
```
This doesn't seem right, though, so I won't close the issue.

**Comment by PhiloNL** [comment]
@jamesblackwell `public User | int $user;` should do the trick. Livewire first sets the ID before resolving the model.

**Comment by johnvdvaart** [comment]
@PhiloNL Your suggestion does not work for me for some reason (Laravel 10). The only obvious difference here is that I am using UUID id type, so I declare it as string type:

```
public User | string $user;
```

Later on when using the user model:

```Error
Call to a member function relationship() on string
```
