### ISSUE TITLE
Pressing Escape key makes rapid requests, even with no modals open

### ISSUE THREAD

**Issue by kamilst96** [wire-elements/modal#214]
Issue: When pressing Escape key, the app makes requests, even when no modals are open.
When holding the key, it becomes a horse race on network tab.

If I understand correctly, this is because of some kind of shared event listener.
Would it be possible to track how many modals are open, and skip requests if there is none?
Alternatively, maybe some kind of throttling, if the first option is not viable.

**Comment by philc-d** [comment]
+1 for this issue, the escape key shouldn't fire an ajax requests when no modals are open. 

Changing ```keydown``` to ```keyup``` below would be a quick way to prevent holding down Escape firing off loads of requests.

![image](https://user-images.githubusercontent.com/57732779/162999933-6721f03f-8e52-44ef-9020-7d107dbceb32.png)

**Comment by PhiloNL** [comment]
Fixed https://github.com/wire-elements/modal/releases/tag/1.0.6 
Thanks for reporting
