### ISSUE TITLE
Does not implement [LivewireUI\Modal\Contracts\ModalComponent] interface.

### ISSUE THREAD

**Issue by marcwitteveen** [wire-elements/modal#215]
I extended from ModalComponent but still I am getting an error "Exception
[App\Http\Livewire\EditPriceAlertException] does not implement [LivewireUI\Modal\Contracts\ModalComponent] interface."

Anybody can point me in the right direction to solve this?

```
<?php

namespace App\Http\Livewire;

use LivewireUI\Modal\ModalComponent;

class EditPriceAlertException extends ModalComponent
{
    public function render()
    {
        return view('livewire.edit-price-alert-exception');
    }
}
```

**Comment by PhiloNL** [comment]
That's strange, this should work. Have you tried a fresh install of Laravel & Livewire to rule out any influence by your existing codebase or third-party packages by any chance? That would help to debug.
