### ISSUE TITLE
Modal not appearing, only the backdrop is showing

### ISSUE THREAD

**Issue by haztakki** [wire-elements/modal#244]
Hello,

I am having issues getting the **Modal** to work. Although it seems a minor issue, I'm starting to go round in circles. I've followed the installation guide correctly. I've even tried publish the assets and injecting the JS myself, but no matter what I do. The modal does not show, only the backdrop is showing. No related errors, except for one about WIre UI.

`Alpine Expression Error: wireui_modal is not defined`

```
<wireui:scripts />

@livewire('livewire-ui-modal')
```

```
"@tailwindcss/aspect-ratio": "^0.4.0",
"@tailwindcss/forms": "^0.5.2",
"@tailwindcss/line-clamp": "^0.4.0",
"@tailwindcss/typography": "^0.5.2",
"tailwindcss": "^3.1.4",
"alpinejs": "^3.10.2",

"laravel/framework": "^9.0",
"wire-elements/modal": "^1.0.7",
"wireui/wireui": "^1.12.1",
```

Cheers!

**Comment by gdebrauwer** [comment]
I'm having the same issue. I see the backdrop, but not the modal itself. I only see the modal if I'm on small device. @HazJ Did you find the issue? Because I have tried lots of things and nothing works 😭

**Comment by inDeev** [comment]
Why this is closed, issue is still there...

**Comment by PhiloNL** [comment]
@gdebrauwer @inDeev, the package referenced above, 'wireui/wireui' is a different modal component. For the width issue, make sure you add the classes to the Tailwind safelist (https://github.com/wire-elements/modal/issues/65#issuecomment-1212086420)

**Comment by gdebrauwer** [comment]
In my case, I have only installed `wire-elements/modal` and I whitelisted the tailwind classes, but still the modal did not show

**Comment by inDeev** [comment]
@gdebrauwer, did you whitelisted it in this way?
```
module.exports = {
    purge: {
        content: [
            './storage/framework/views/*.php',
            './resources/**/*.blade.php',
            './resources/**/*.js',
            './resources/**/*.vue',
        ],
        options: {
            safelist: [
                "sm:max-w-sm",
                "sm:max-w-md",
                "md:max-w-lg",
                "md:max-w-xl",
                "lg:max-w-2xl",
                "lg:max-w-3xl",
                "xl:max-w-4xl",
                "xl:max-w-5xl",
                "2xl:max-w-6xl",
                "2xl:max-w-7xl",
            ]
        },
    },
    theme: {
       ...
```

**Comment by iambateman** [comment]
Update in 2023...I think the safelist option is moved. This worked for me...

```
module.exports = {
  safelist: [
    "sm:max-w-sm",
                "sm:max-w-md",
                "md:max-w-lg",
                "md:max-w-xl",
                "lg:max-w-2xl",
                "lg:max-w-3xl",
                "xl:max-w-4xl",
                "xl:max-w-5xl",
                "2xl:max-w-6xl",
                "2xl:max-w-7xl",
      ]
}
