### ISSUE TITLE
After closing the Modal it won't Open again 

### ISSUE THREAD

**Issue by mihirhirpara** [wire-elements/modal#245]
I'm having a strange error, after closing down a modal it won't open again and completely freezes the page:

https://user-images.githubusercontent.com/67440708/182307804-4b71b2ab-04e0-4361-8efe-d5b098d225b9.mp4

I have removed Alpine CDN since I already have it loading from the node modules folder. This was the only solution I found and it is still not working. Any help will be appreactied. 

Thank You

**Comment by mihirhirpara** [comment]
Solved: 
Alpine was loading from livewire-powergrid too. After commenting the CDN link in config file it works.

**Comment by TrevorIkky** [comment]
> Solved:
> Alpine was loading from livewire-powergrid too. After commenting the CDN link in config file it works.

in config/livewire-powergrid.php change this line to 'alpinejs_cdn' => null,
