### ISSUE TITLE
display modal on page load

### ISSUE THREAD

**Issue by krutsednar** [wire-elements/modal#272]
how can I display the modal once the page loads?

**Comment by krutsednar** [comment]
solved it whit below code

<script>

    window.addEventListener('load', ()=>{
        Livewire.emit('openModal', 'reminder-modal');
    })

</script>

**Comment by ghaskell** [comment]
Thanks @krutsednar.  Don't know why this didn't occur to me sooner...  abstracted to:
`        <script> window.addEventListener('load', ()=>{ Livewire.emit('showInitialModal'); }) </script>
`
and added to my layout with listener for showInitialModal.
