### ISSUE TITLE
How to get Js components (like Select2, tom-select...) to fully work inside the modal

### ISSUE THREAD

**Issue by DAH-hub** [wire-elements/modal#273]
Hi there,
Thx for the package,
.
Plz, How to get a Js component, like Select2, tom-select... to fully work inside the modal.
.
The blade looks like :
.
div wire:ignore
select id="users" wire:model.defer="users" class="tom-select" multiple
  @foreach($user_list as $key => $value)
    option value="{{ $key }}"> {{ $value }} /option
  https://github.com/Endforeach
/select
/div
.
Like this, the tom-select isn't working

Thanks

**Comment by PhiloNL** [comment]
Use Livewire Javascript [hooks](https://laravel-livewire.com/docs/2.x/lifecycle-hooks#js-hooks) too initiate any javascript.

**Comment by DAH-hub** [comment]
Thx a lot :)
