### ISSUE TITLE
Modal Not Working in Laravel 10

### ISSUE THREAD

**Issue by ambrosethebuild** [wire-elements/modal#305]
Hi tried the free modal component with my new laravel 10 project and it didn't work, so i bought the pro license thinking the pro might be up-to-date with new laravel version, but still i can't get the model to work with my project.

`
<button wire:click="$emit('modal.open', 'hello-world')">Open Modal</button>
`

Also use this action:
`
    <div class="border-b p-4 flex space-between justify-between">
        <p class="text-2xl font-bold ">Projects</p>
        <x-buttons.primary class="p-2 h-8" wireClick="$emit('modal.open', 'app.admin.modals.project.create-project')" text="Create" />
    </div>
`

I have the modal component already for both the HelloWord and CreateProject.

**Comment by Africanpride** [comment]
Hello. Could you share the exact error it is throwing?.

**Comment by ambrosethebuild** [comment]
Working now. I had to reinstall the right versions of tailwindcss and alphine.js.
Initially, I installed the latest livewire version which comes with alphine included.

But for the Pro version, still not able to get it to work. Modal shows at the bottom of the page not as a modal

**Comment by Africanpride** [comment]
Noted 👍

**Comment by PhiloNL** [comment]
@ambrosethebuild if the modal shows at the bottom, the CSS is often omitted, ensure you import the required CSS as shown in the [demo repository](https://github.com/wire-elements/pro-demo/blob/main/resources/css/app.css).

Feel free to contact support@wire-elements.dev if you still have a problem with getting the pro version to work.
