### ISSUE TITLE
[Feature] Create trait of ModalComponent for easy implementation?

### ISSUE THREAD

**Issue by coffeeyoghurt** [wire-elements/modal#319]
Hi there, 

Would it be an idea to move all the code in `ModalComponent.php` to a trait and make the existing component use the trait? This would allow anyone to use the trait instead of extending `ModalComponent`. 

```
trait InteractsWithModal
{
    /* all code of ModalComponent here */
}
```

```
class ModalComponent implements \LivewireUI\Modal\Contracts\ModalComponent
{
    use InteractsWithModal;
    
    /* the rest will be empty */
}
```

**Comment by PhiloNL** [comment]
Thanks! I'll see if this can be added in the next major release.
