### ISSUE TITLE
Feature Request: z-index

### ISSUE THREAD

**Issue by ahosker** [wire-elements/modal#320]
Feature Request: Enable change of z-index in Config and Attributes, similar to modalMaxWidth.

The Tailwind UI template I am using has a sidebar with a z-index of z-50.
This package Modal has a z-index of z-10.
This means the Modal clips under the sidebar.

It would be great to add this feature, but also posting this as a reminder for myself. Time allowing would love to contribute.

**Comment by PhiloNL** [comment]
An idea for a future release. For now, you can publish the views and add your own z-index.
