### ISSUE TITLE
Package installation error on livewire 3@beta

### ISSUE THREAD

**Issue by hsiraaj** [wire-elements/modal#328]
Problem 1
    - wire-elements/modal[0.1.0, ..., 0.1.7, 1.0.0, ..., 1.0.8] require livewire/livewire ^2.0 -> found livewire/livewire[v2.0.0, ..., v2.12.3] but it conflicts with your root composer.json require (^3.0@beta).

**Comment by lrljoe** [comment]
It'd be a bit more work than just changing that I'm afraid!

The way that emit/listener used to work is no more, its now a dispatch/PHP 8.1 attribute.

**Comment by PhiloNL** [comment]
There are still a few v3 bugs besides the changes that need to be fixed. I've been submitting PRs and waiting for these to be merged.

**Comment by lrljoe** [comment]
just a few bugs!  can't help but feel letting more people have alpha copies would have prevented this

**Comment by PhiloNL** [comment]
Added a note about this to inform users https://github.com/wire-elements/modal/discussions/329
