### ISSUE TITLE
Livewire v3 support

### ISSUE THREAD

**Issue by PhiloNL** [wire-elements/modal#330]
[It's work in progress, please read the following announcement](https://github.com/wire-elements/modal/discussions/329)

**Comment by Misagh90** [comment]
What is your approximate time for the release new version?

**Comment by PhiloNL** [comment]
As described in the announcement, there is no estimate at this time, given some things are outside my control (bugs and pending PRs), which must be resolved first to get the components working.

**Comment by PhiloNL** [comment]
[The first beta release is available](https://github.com/wire-elements/modal/discussions/329).

**Comment by ju5t** [comment]
Thanks for the work you're doing @PhiloNL! 👍 

The only suggestion I have is to either introduce a trait or global helper to open modals, instead of directly depending on the logic of Livewire with `$dispatch`. We're avid users of this package (although we also pay for the premium package). This change will be a lot of work for us and not something I would like to do again should there be another breaking change in v4.

If it's not something you're up to, no worries, we'll introduce it in our app ourselves.

**Comment by PhiloNL** [comment]
> Thanks for the work you're doing @PhiloNL! 👍
> 
> The only suggestion I have is to either introduce a trait or global helper to open modals, instead of directly depending on the logic of Livewire with `$dispatch`. We're avid users of this package (although we also pay for the premium package). This change will be a lot of work for us and not something I would like to do again should there be another breaking change in v4.
> 
> If it's not something you're up to, no worries, we'll introduce it in our app ourselves.

No problem @ju5t :)

Yeah, I've been thinking about this as well. Maybe `wire:modal` or something. My first step is to get everything working with v3 before adding new features. Do you have a preferred syntax you would like to see?

I've been working on a regular expression to automate the changes, and I think this one matches the most common occurrences:

```
emit\('(?:openModal|modal.open)', '([^']+)'(?:, (\{[^}]+\}|@js\(\[[^\]]+\]\)))?\)$

$emit('openModal', 'edit-user', {user: 5})
$emit('openModal', 'edit-user', @js(['foo' => 'bar']))

$0 = emit('openModal', 'edit-user', {user: 5})
$1 = edit-user
$2 = {user: 5}

$0 = emit('openModal', 'edit-user', @js(['foo' => 'bar']))
$1 = edit-user
$2 = @js(['foo' => 'bar'])
```

**Comment by ju5t** [comment]
You're doing some absolute regex magic these days!

I'm OK with any solution. Personally I would probably write a macro or have a trait with the `modal` method which accepts the component and the parameters. Something like that would work for me :)

**Comment by PhiloNL** [comment]
@ju5t these complex ones are mostly ChatGTP work haha. I've just [added a PR](https://github.com/livewire/livewire/pull/5994) that will allow me to hook into the `livewire:upgrade` command and add this automation.

Thanks for your input 😄
