### ISSUE TITLE
Reference a livewire component by key

### ISSUE THREAD

**Issue by bilogic** [wire-elements/modal#335]
1. I have a Livewire component residing in a package, but has been registered by using `Livewire::component("key", Component::class);`
2. When I called `$dispatch('openModal', {component: 'key'})`, I get the exception `Unable to find component: [key]`
3. Is there way to reference the Livewire component by its `key`?

**Comment by PhiloNL** [comment]
This should work. Are you able to include the component manually in your project? e.g. `@livewire('key')`?

**Comment by bilogic** [comment]
Yes, what I wrote was `@livewire('key')` in order to call the modal 

When I save my class here `\Me\MyPackage\Http\Livewire\Component` -> gives me `Unable to find component: [key]`.
When I save my class here `\App\Http\Livewire\Component` -> works

**Comment by bilogic** [comment]
I tested again. It seems to work now, must have been my issue. Sorry about this.
