### ISSUE TITLE
Issue with navigate ? 

### ISSUE THREAD

**Issue by yooplait** [wire-elements/modal#340]
Good morning,

I have a problem, I don't know why.

When I use wire:navigate to switch pages and return to the page containing my button, I get an error when I click:

@click="$dispatch('openModal', { component: 'file-upload', 'arguments': {{ json_encode(['uuid' => $root->uuid]) }} })"

Do you know why ?

<img width="449" alt="image" src="https://github.com/wire-elements/modal/assets/25279695/7bae1ffd-f228-4e5c-9704-8b6b39135384">

Thank you !

**Comment by PhiloNL** [comment]
Hi there,
This is related to wire:navigate. This feature is somewhat unstable and various reports have been reported. Hopefully, this problem will be resolved in future Livewire beta releases.

**Comment by yooplait** [comment]
Hi :)

The problem seems to disappear when we add @persist around the modal component :)

**Comment by yooplait** [comment]
I thought I had solved the problem but... no.

Can you just confirm that you also have this problem?

Good day to you

**Comment by yooplait** [comment]
Perfect, thank you so much :)

**Comment by DanielSpravtsev** [comment]
Same problem but I found a workaround. 
You can incapsulate <livewire:wire-elements-modal/> into @persist to fix this problem :) 

@yooplait @PhiloNL 

``` 
views/layouts/app.blade.php:

<body class="h-full">
    @yield('content')

    @persist('modal')
        <livewire:wire-elements-modal/>
    @endpersist
</body>
```

**Comment by PhiloNL** [comment]
@DanielSpravtsev yeah, I also tried that yesterday, but it doesn't fix all the issues. If you navigate between a few pages, the modal might still fail with a weird promise error in your console. The navigate feature still has a few bugs.

**Comment by DanielSpravtsev** [comment]
@PhiloNL It is weird, because I don't  have this issues, all works fine with page navigation and modal component usages on every page 😅

**Comment by yooplait** [comment]
Why is this closed ? Fixed sinde beta v9 ? Thank you !
