### ISSUE TITLE
i have a problem while updating to beta version

### ISSUE THREAD

**Issue by abdouchamkha** [wire-elements/modal#341]
![image](https://github.com/wire-elements/modal/assets/75368032/85df1f78-e8ee-4609-98fb-3da0930a2ab4)
![image](https://github.com/wire-elements/modal/assets/75368032/4f5cb06f-0d28-4291-90c5-7090214f3fe4)

**Comment by Nathan269** [comment]
I am also receiving the same error. Is there any update on this?

**Comment by PhiloNL** [comment]
Works fine for me on MacOS so I think it's related to Windows.
The composer docs state the [following](https://getcomposer.org/doc/articles/versions.md#caret-version-range-):

> Note: If you are using PowerShell on Windows, you have to escape carets when using them as argument on the CLI for example when using the composer require command. You have to use four subsequent caret operators, e.g. ^^^^1.2.3, to ensure the caret operator gets passed to Composer correctly.

So make sure to escape the caret operator or add `"wire-elements/modal": "^2.0@beta"` manually to your composer.json and run `composer update wire-elements/modal`.

**Comment by Nathan269** [comment]
Thanks for the quick response @PhiloNL I no longer have the issue.
