### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by flatcapco** [wire-elements/modal#345]
` Method Livewire\Features\SupportConsoleCommands\Commands\UpgradeCommand::addThirdPartyUpgradeStep does not exist.
`

I receive the issue above when trying to install the latest version of this package with the latest version of the livewire 3 beta. My install has been migrated from livewire 2.

When I remove this package composer update starts working again

Any thoughts appreciated

**Comment by PhiloNL** [comment]
Please update to the latest version of the Livewire beta. It looks like you are using an older version

**Comment by flatcapco** [comment]
Sorry yep thats me being stupid beta.6 resolved it
