### ISSUE TITLE
Component with @push

### ISSUE THREAD

**Issue by dgironella** [wire-elements/modal#347]
Hello,

I have a Livewire component that contains JavaScript, which I push using @push('scripts'). When I use this component on any page, it functions as expected. However, if the component is used within an openModal, the JavaScript doesn't load. I noticed this issue after upgrading to Livewire v3. In v2, the component worked both outside and within modals. Also, when I nest this component inside a parent component, it functions properly.

Can anyone help identify the problem?

**Comment by dgironella** [comment]
An example, for a simple component:

`<div>
    <button onclick="testIt()">Test</button>
    @push('scripts')
        <script>
            function testIt()
            {
                console.log('Ok work');
            }
        </script>
    @endpush
</div>
`

If I use this component like `@livewire('test')` is working correctly.

But if I use it like: `<button onclick="Livewire.dispatch('openModal', { component: 'test'})">Open Imatge</button>`

Javascript @push is not processed. And component not work.

**Comment by PhiloNL** [comment]
`@push` doesn't work inside modals because the main layout is already rendered. This also didn't work in v2. I recommend adding your scripts to `app.js` so that they are globally available.

**Comment by ignacioOptinet** [comment]
That used to work in v2, 100%.

**Comment by l3eto** [comment]
having same problem, some alternative? i dont want to add some big script for all website, only load first when navigated to some especific page

**Comment by jamesautodude** [comment]
> having same problem, some alternative? i dont want to add some big script for all website, only load first when navigated to some especific page

Did you figure something out? I'm stuck as well because my textarea is within the modal component and even setting things globally doesn't work into the modal component :/

**Comment by PhiloNL** [comment]
> > having same problem, some alternative? i dont want to add some big script for all website, only load first when navigated to some especific page
> 
> Did you figure something out? I'm stuck as well because my textarea (ckeditor) is within the modal component and even setting things globally doesn't work into the modal component :/

Livewire works best with AlpineJS, any alpine invocation is triggered when a modal is opened.
So you can do something like`<div x-init="ClassicEditor.create(...)">`

**Comment by jamesautodude** [comment]
I figured out a better approach as sometimes I can't include the JavaScript globally, other times using alpine just doesn't seem to work right for me.

The better approach is dispatching...

Put your typical @push code in your global scripts under a dispatch so it's accessible but doesn't fire until called, and then when opening the modal, fire the dispatch in the mount method

This helped me fix an issue with using Stripe inside a wire-elements modal

Just in case someone comes across this in the future
