### ISSUE TITLE
Livewire 3 closeModal closing issue

### ISSUE THREAD

**Issue by AEastwood** [wire-elements/modal#357]
The closeModal even works perfectly however if I spawn a child modal then close that then spawn it, then close it, rinse and repeat a few times then the main modal takes multiple clicks on the close button to close the original modal

```html
  <div class="flex w-full mb-7">
      <div class="w-1/2 text-2xl dark:text-white">
          Teams
      </div>

      <div class="w-1/2 text-right">
          <button
              class="font-bold hover:bg-gray-100 dark:bg-gray-800 hover:dark:bg-gray-900 dark:text-white px-3 py-1.5 rounded"
              title="Close"
              tabindex="0"
              onclick="Livewire.dispatch('closeModal')"
          >
              X
          </button>
      </div>
  </div>
```

Laravel 10
Livewire 3

**Comment by PhiloNL** [comment]
Can you try and see if this is still in issue with the latest release? Thanks!

**Comment by AEastwood** [comment]
> Can you try and see if this is still in issue with the latest release? Thanks!

Just update to version 2.0.8 and it seems to have resolved it.

I'll let you know if any further issue(s).
