### ISSUE TITLE
Call to a member function mapWithKeys() on null when using Confirmation modal

### ISSUE THREAD

**Issue by createdatasystems-george** [wire-elements/modal#358]
Hello, when using the confirmation modal (code copied from docs) i get the following error thrown: `Call to a member function mapWithKeys() on null `. Any ideas? Thanks

**Comment by PhiloNL** [comment]
Hi @createdatasystems-george,
This repository is for the regular component and the feature you are referencing is for the pro version.

If I copy and paste the code from the docs, the confirmation modal shows just fine. So it must be related to your project.
If you can reach out to support@wire-elements.dev and share some more details about the problem, that would be great.
