### ISSUE TITLE
Prevent modal from closing when clicked away

### ISSUE THREAD

**Issue by francisnnumbi** [wire-elements/modal#360]
I have seen a hidden attribute that sets **close_modal_on_click_away** to **true**. But I find miself in a situation where I should prevent it from closing if the user by mistake clicks away, as this will lose anything that was being recorded there. Is it possible to set this attribute accessible so that the behavior be changed when needed ?

**Comment by AEastwood** [comment]
You may use these two functions to achieve this:

```php
     /**
     * @return bool
     */
    public static function closeModalOnClickAway(): bool
    {
        return false;
    }

    /**
     * @return bool
     */
    public static function closeModalOnEscape(): bool
    {
        return false;
    }
```

**Comment by francisnnumbi** [comment]
Thank you very much

**Comment by Sans84** [comment]
> ```
> closeModalOnClickAway
> ```

Doesn't work for me (`"wire-elements/pro": "^4.0"`)

**Comment by da-sie** [comment]
Add in Modal component following method:

```
    public static function behavior():array
    {
        return [
                'close-on-escape' => true,
                'close-on-backdrop-click' => false,
                'trap-focus' => true,
                'remove-state-on-close' => false,
        ];
    }
```
