### ISSUE TITLE
Only arrays and Traversables can be unpacked issue

### ISSUE THREAD

**Issue by nikola-n** [wire-elements/modal#369]
Hi all, I'm experiencing this issue when I have the dispatch close event enabled, and I'm using Livewire 3:

```
public static function dispatchCloseEvent(): bool
    {
        return true;
    }
```

Then I have the `modalClosed` event added in the listeners and I have a method with the same name:

```
  /**
     * @var string[]
     */
    public $listeners = [
        'modalClosed',
    ];
```

When the modal is invoked and I close it I get this kind of issue.
<img width="697" alt="image" src="https://github.com/wire-elements/modal/assets/58821667/1766398e-8201-4465-a330-c4545336dccf">

Do you have any ideas or suggestions on how I can fix this? Thanks!

**Comment by nikola-n** [comment]
I think that these PR's should fix the issue:

- https://github.com/wire-elements/modal/pull/371

- https://github.com/wire-elements/modal/pull/380

**Comment by PhiloNL** [comment]
Fixed in the latest release.
