### ISSUE TITLE
How to open additional modal from modal?

### ISSUE THREAD

**Issue by stojankukrika** [wire-elements/modal#383]
Hi,
How to open modal from modal and close parent modal? Or How to close current modal and open new one.

My scenario is: user click on generate some token, and I like to show him a new token in new modal because I do not want to show token in the past, just that time it will shows up and will be masked in future. To prevent hackers to use it again in some other places.

Is that possible?

Best regards and thank you fro this package, it's AWESOME!

**Comment by Krato** [comment]
@PhiloNL After upgrade to v2 using Livewire 3, this is not working. Can you check it please?

Thank you!

**Comment by GBry** [comment]
Having the same error. The thing is, it's not happening on *every* modal, another one where I implemented a two step modal works.

**Comment by PhiloNL** [comment]
Can you give this a try in the latest release? Thanks!

**Comment by PhiloNL** [comment]
If this still occurs, let me know.

**Comment by fkhrdinn** [comment]
> Can you give this a try in the latest release? Thanks!

Hi, I encountered the same problem like the author stated. First modal went to hide but second one is not showing and gave the same js error. Uncaught TypeError: Cannot read properties of null (reading 'before').

<img width="362" alt="ggg" src="https://github.com/wire-elements/modal/assets/90583623/b5809f76-4c87-45a4-bca1-b5159617318a">

**Comment by camerontucker** [comment]
@fkhrdinn try changing inject_morph_markers => false in livewire.php. This fixed my error, which only happens in production.

FWIW https://github.com/livewire/livewire/discussions/6965

**Comment by GBry** [comment]
@PhiloNL Haven't been happening since, happens just now. Weirdly enough, it's a whole different modal and child-modal. I can confirm that the child-modal works when not spawning from a parent modal (standalone)

@camerontucker your suggestion... didn't work. After changing that, and reclearing config and cache, no change.
