### ISSUE TITLE
Latest compiled component path not found.

### ISSUE THREAD

**Issue by hazratmilad** [wire-elements/modal#436]
we get 

  Latest compiled component path not found.

  at vendor/livewire/livewire/src/Mechanisms/ExtendBlade/DeterministicBladeKeys.php:16
     12▕ 
     13▕     public function generate()
     14▕     {
     15▕         if (! $this->lastPath) {
  ➜  16▕             throw new \Exception('Latest compiled component path not found.');
     17▕         }
     18▕ 
     19▕         $path = $this->lastPath;
     20▕         $count = $this->counter();

      +9 vendor frames 

  10  [internal]:0
      Illuminate\Foundation\Console\ViewCacheCommand::Illuminate\Foundation\Console\{closure}(Object(Symfony\Component\Finder\SplFileInfo), "/Users/milad/PhpstormProjects/bludex-api/resources/views/components/layouts/app.blade.php")
      +35 vendor frames 

  46  artisan:13
      Illuminate\Foundation\Application::handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))

when execute

php artisan optimize

fail in views

**Comment by PhiloNL** [comment]
This is related to Livewire and not this package. Please report your issue to the Livewire repositories.
