### ISSUE TITLE
"wire-elements pro", can't get it to work out of the box...

### ISSUE THREAD

**Issue by jamesautodude** [wire-elements/modal#470]
Laravel 11
Livewire 3.5

I purchased the pro version, which the documentation on there seems to be outdated... Came to here to see updated instructions, which I was able to follow better, but still can't get it to work.

I get these errors in console right now:

module.esm.js:433 Alpine Expression Error: Illegal invocation

Expression: "open"

 div.wep-modal
lt @ module.esm.js:433
Tl @ module.esm.js:425
(anonymous) @ module.esm.js:3096
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
(anonymous) @ module.esm.js:3096
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52Understand this warning
module.esm.js:433 Alpine Expression Error: Illegal invocation

Expression: "open"

 div.wep-modal-backdrop
lt @ module.esm.js:433
Tl @ module.esm.js:425
(anonymous) @ module.esm.js:3096
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
(anonymous) @ module.esm.js:3096
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52Understand this warning
module.esm.js:433 Alpine Expression Error: WepOverlayComponent is not defined

Expression: "WepOverlayComponent({ type: 'modal', animationOverlapDuration: 350 })"

 <div wire:snapshot=​"{"data":​{"activeComponent":​null,"components":​[[]​,{"s":​"arr"}​]​}​,"memo":​{"id":​"qncB2dkCu8pduwUn8RMN","name":​"modal-pro","path":​"owner\/​litters","method":​"GET","children":​[]​,"scripts":​[]​,"assets":​[]​,"errors":​[]​,"locale":​"en"}​,"checksum":​"6db186e4a481df0b13d9d5b1ac8a9c1def2e345404ce448a3b009770ccef5abf"}​" wire:effects=​"{"listeners":​["modal.open"]​}​" wire:id=​"qncB2dkCu8pduwUn8RMN" x-data=​"WepOverlayComponent({ type:​ 'modal', animationOverlapDuration:​ 350 }​)​" @keydown.window.escape=​"closeIf('close-on-escape')​" x-show=​"open" class=​"wep-modal" :class=​"getElementAttribute('component-class')​" aria-modal=​"true">​…​</div>​
lt @ module.esm.js:433
(anonymous) @ module.esm.js:511
Promise.catch
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
Ee @ module.esm.js:452
(anonymous) @ module.esm.js:3029
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52Understand this warning
module.esm.js:433 Alpine Expression Error: getElementAttribute is not defined

Expression: "getElementAttribute('component-class')"

 <div wire:snapshot=​"{"data":​{"activeComponent":​null,"components":​[[]​,{"s":​"arr"}​]​}​,"memo":​{"id":​"qncB2dkCu8pduwUn8RMN","name":​"modal-pro","path":​"owner\/​litters","method":​"GET","children":​[]​,"scripts":​[]​,"assets":​[]​,"errors":​[]​,"locale":​"en"}​,"checksum":​"6db186e4a481df0b13d9d5b1ac8a9c1def2e345404ce448a3b009770ccef5abf"}​" wire:effects=​"{"listeners":​["modal.open"]​}​" wire:id=​"qncB2dkCu8pduwUn8RMN" x-data=​"WepOverlayComponent({ type:​ 'modal', animationOverlapDuration:​ 350 }​)​" @keydown.window.escape=​"closeIf('close-on-escape')​" x-show=​"open" class=​"wep-modal" :class=​"getElementAttribute('component-class')​" aria-modal=​"true">​…​</div>​
lt @ module.esm.js:433
(anonymous) @ module.esm.js:511
Promise.catch
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
(anonymous) @ module.esm.js:2996
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
Ho @ module.esm.js:2996
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52Understand this warning
module.esm.js:433 Alpine Expression Error: activeComponentWidth is not defined

Expression: "activeComponentWidth"

 <div x-show=​"open && showActiveComponent" x-transition:enter=​"enter" x-transition:enter-start=​"start" x-transition:enter-end=​"end" x-transition:leave=​"leave" x-transition:leave-start=​"start" x-transition:leave-end=​"end" x-bind:class=​"activeComponentWidth" x-trap.inert.noscroll=​"getElementBehavior('trap-focus')​ && open" class=​"wep-modal-content" style=​"display:​ none;​">​…​</div>​
lt @ module.esm.js:433
(anonymous) @ module.esm.js:511
Promise.catch
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
(anonymous) @ module.esm.js:2996
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
Ho @ module.esm.js:2996
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52Understand this warning
module.esm.js:433 Alpine Expression Error: showActiveComponent is not defined

Expression: "open && showActiveComponent"

 <div x-show=​"open && showActiveComponent" x-transition:enter=​"enter" x-transition:enter-start=​"start" x-transition:enter-end=​"end" x-transition:leave=​"leave" x-transition:leave-start=​"start" x-transition:leave-end=​"end" x-bind:class=​"activeComponentWidth" x-trap.inert.noscroll=​"getElementBehavior('trap-focus')​ && open" class=​"wep-modal-content" style=​"display:​ none;​">​…​</div>​
lt @ module.esm.js:433
(anonymous) @ module.esm.js:511
Promise.catch
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
(anonymous) @ module.esm.js:3096
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
(anonymous) @ module.esm.js:3096
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52Understand this warning
module.esm.js:433 Alpine Expression Error: getElementBehavior is not defined

Expression: "getElementBehavior('trap-focus') && open"

 <div x-show=​"open && showActiveComponent" x-transition:enter=​"enter" x-transition:enter-start=​"start" x-transition:enter-end=​"end" x-transition:leave=​"leave" x-transition:leave-start=​"start" x-transition:leave-end=​"end" x-bind:class=​"activeComponentWidth" x-trap.inert.noscroll=​"getElementBehavior('trap-focus')​ && open" class=​"wep-modal-content" style=​"display:​ none;​">​…​</div>​
lt @ module.esm.js:433
(anonymous) @ module.esm.js:511
Promise.catch
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
(anonymous) @ module.esm.js:943
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
Kc.e.directive.e.skipDuringClone.expression @ module.esm.js:943
(anonymous) @ module.esm.js:1241
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52
Show 2 more frames
Show lessUnderstand this warning
2module.esm.js:525 Uncaught TypeError: Illegal invocation
    at Mt (module.esm.js:525:24)
    at module.esm.js:513:9
    at Tl (module.esm.js:423:12)
    at module.esm.js:3096:17
    at r (module.esm.js:1785:16)
    at Object.ku [as effect] (module.esm.js:1760:5)
    at Te (module.esm.js:51:33)
    at module.esm.js:67:27
    at Function.<anonymous> (module.esm.js:3096:3)
    at r (module.esm.js:598:45)
Mt @ module.esm.js:525
(anonymous) @ module.esm.js:513
Tl @ module.esm.js:423
(anonymous) @ module.esm.js:3096
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
(anonymous) @ module.esm.js:3096
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52
setTimeout
lt @ module.esm.js:436
Tl @ module.esm.js:425
(anonymous) @ module.esm.js:3096
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
(anonymous) @ module.esm.js:3096
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52Understand this error
module.esm.js:437 Uncaught ReferenceError: WepOverlayComponent is not defined
    at [Alpine] WepOverlayComponent({ type: 'modal', animationOverlapDuration: 350 }) (eval at <anonymous> (https://example.com/livewire/livewire.min.js?id=923613aa:5:668), <anonymous>:3:16)
    at module.esm.js:511:21
    at Tl (module.esm.js:423:12)
    at Ee (module.esm.js:452:31)
    at Function.<anonymous> (module.esm.js:3029:15)
    at r (module.esm.js:598:45)
    at n (module.esm.js:603:5)
    at Il (module.esm.js:606:3)
    at ie (module.esm.js:804:3)
    at module.esm.js:756:5
[Alpine] WepOverlayComponent({ type: 'modal', animationOverlapDuration: 350 }) @ VM513:3
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
Ee @ module.esm.js:452
(anonymous) @ module.esm.js:3029
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52
setTimeout
lt @ module.esm.js:436
(anonymous) @ module.esm.js:511
Promise.catch
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
Ee @ module.esm.js:452
(anonymous) @ module.esm.js:3029
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52Understand this error
module.esm.js:437 Uncaught ReferenceError: getElementAttribute is not defined
    at [Alpine] getElementAttribute('component-class') (eval at <anonymous> (https://example.com/livewire/livewire.min.js?id=923613aa:5:668), <anonymous>:3:16)
    at module.esm.js:511:21
    at Tl (module.esm.js:423:12)
    at module.esm.js:2996:17
    at r (module.esm.js:1785:16)
    at Object.ku [as effect] (module.esm.js:1760:5)
    at Te (module.esm.js:51:33)
    at module.esm.js:67:27
    at Function.Ho (module.esm.js:2996:3)
    at r (module.esm.js:598:45)
[Alpine] getElementAttribute('component-class') @ VM514:3
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
(anonymous) @ module.esm.js:2996
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
Ho @ module.esm.js:2996
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52
setTimeout
lt @ module.esm.js:436
(anonymous) @ module.esm.js:511
Promise.catch
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
(anonymous) @ module.esm.js:2996
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
Ho @ module.esm.js:2996
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52Understand this error
module.esm.js:437 Uncaught ReferenceError: activeComponentWidth is not defined
    at [Alpine] activeComponentWidth (eval at <anonymous> (module.esm.js:486:19), <anonymous>:3:32)
    at module.esm.js:511:21
    at Tl (module.esm.js:423:12)
    at module.esm.js:2996:17
    at r (module.esm.js:1785:16)
    at Object.ku [as effect] (module.esm.js:1760:5)
    at Te (module.esm.js:51:33)
    at module.esm.js:67:27
    at Function.Ho (module.esm.js:2996:3)
    at r (module.esm.js:598:45)
[Alpine] activeComponentWidth @ VM517:3
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
(anonymous) @ module.esm.js:2996
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
Ho @ module.esm.js:2996
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52
setTimeout
lt @ module.esm.js:436
(anonymous) @ module.esm.js:511
Promise.catch
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
(anonymous) @ module.esm.js:2996
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
Ho @ module.esm.js:2996
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52Understand this error
module.esm.js:437 Uncaught ReferenceError: showActiveComponent is not defined
    at [Alpine] open && showActiveComponent (eval at <anonymous> (module.esm.js:486:19), <anonymous>:3:40)
    at module.esm.js:511:21
    at Tl (module.esm.js:423:12)
    at module.esm.js:3096:17
    at r (module.esm.js:1785:16)
    at Object.ku [as effect] (module.esm.js:1760:5)
    at Te (module.esm.js:51:33)
    at module.esm.js:67:27
    at Function.<anonymous> (module.esm.js:3096:3)
    at r (module.esm.js:598:45)
[Alpine] open && showActiveComponent @ VM518:3
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
(anonymous) @ module.esm.js:3096
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
(anonymous) @ module.esm.js:3096
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52
setTimeout
lt @ module.esm.js:436
(anonymous) @ module.esm.js:511
Promise.catch
(anonymous) @ module.esm.js:511
Tl @ module.esm.js:423
(anonymous) @ module.esm.js:3096
r @ module.esm.js:1785
ku @ module.esm.js:1760
Te @ module.esm.js:51
(anonymous) @ module.esm.js:67
(anonymous) @ module.esm.js:3096
r @ module.esm.js:598
n @ module.esm.js:603
Il @ module.esm.js:606
ie @ module.esm.js:804
(anonymous) @ module.esm.js:756
Bl @ module.esm.js:755
Da @ lifecycle.js:88
(anonymous) @ index.js:52Understand this error
module.esm.js:437 Uncaught ReferenceError: getElementBehavior is not defined
    at [Alpine] getElementBehavior('trap-focus') && open (eval at <anonymous> (https://example.com/livewire/livewire.min.js?id=923613aa:5:668), <anonymous>:3:16)
    at module.esm.js:511:21
    at Tl (module.esm.js:423:12)
    at module.esm.js:943:20
    at r (module.esm.js:1785:16)
    at Object.ku [as effect] (module.esm.js:1760:5)
    at Te (module.esm.js:51:33)
    at module.esm.js:67:27
    at Kc.e.directive.e.skipDuringClone.expression (module.esm.js:943:7)
    at Function.<anonymous> (module.esm.js:1241:55)

**Comment by jamesautodude** [comment]
I ended up having to use AI to fix this hahaha

So you have to use:

@wireElementsStyles in head
@wireElementsScripts at end of body

That's what ultimately fixed it for me, for now

**Comment by PhiloNL** [comment]
That would be very strange as `@wireElementsStyles` and `@wireElementsScripts` don't exist 😅 
It looks like you might have loaded Alpine twice or have not included the required Javascript files.
Please see the demo repository as a reference: https://github.com/wire-elements/pro-demo

**Comment by jamesautodude** [comment]
@PhiloNL 

Interesting lol. It never worked so I guess that makes sense

I first had just:
@LivewireScripts
@livewire('modal-pro')

That's what gives me all the errors

But I'm also on Laravel 11 and the instructions for wire-elements pro doesn't match. Like it says to put something in my config/app file but I believe that moved to bootstrap/providers

**Comment by jamesautodude** [comment]
I cloned the repo and attempted to use it, upon clicking "login" on the laravel home page, I get this error:

`Unable to locate a class or view for component [jet-authentication-card-logo].`

Also `npm run build` doesn't work lol

**Comment by jamesautodude** [comment]
Looks like the Pro demo has some typos :)

On the login view, it has `<x-jet` for the components, removing `-jet` fixes those errors

The instructions are missing some steps :)

- cp .env.example .env
- put database details in .env file
- composer install
- php artisan key:generate
- php artisan migrate --seed
- npm install
- npm run build

Past that, after logging in, I'm only seeing a repositories tab that shows changelogs? I don't see any modal examples or anything :/

**Comment by jamesautodude** [comment]
So I'm getting somewhere now, but come to find out, the version doesn't match between the Pro Demo repo and the 4.0 wire-elements version which may be causing this next issue. It's set as @dev for the version in the Pro Demo.

Past that, the main problem is publishing assets right now, at least in Version 4...

`php artisan vendor:publish --tag=wire-elements-pro-assets`

That command doesn't have all the files. I go to run `npm run build` and get:
```
Could not resolve '../../vendor/wire-elements/pro/resources/js/overlay-component' from resources/js/app.js
error during build:
Error: Could not resolve '../../vendor/wire-elements/pro/resources/js/overlay-component' from resources/js/app.js
```

I'll try copying that file from the demo repo for now and go from there...

**Comment by jamesautodude** [comment]
For anyone coming across this later, this is what I had to do in my project so far to get things working for the `Pro version`

This is what I had to do:

### composer.json file
- Change "wire-elements/pro" to "*@dev" (instead of "^4.0")
- Run `composer install`
- Run `php artisan vendor:publish --tag=wire-elements-pro-assets`

### package.json file
- Add `"textarea-caret": "^3.1.0"`
- Run `npm install`

### resources/js/app.js
- Add the following lines:
```
import '../../vendor/wire-elements/pro/resources/js/overlay-component'
import '../../vendor/wire-elements/pro/resources/js/spotlight-component'
import '../../vendor/wire-elements/pro/resources/js/insert-component'
```

### resources/cs/app.css
- Add the following lines:
@import "../../vendor/wire-elements/pro/resources/css/tailwind/spotlight-component.css";
@import "../../vendor/wire-elements/pro/resources/css/tailwind/overlay-component.css";
@import "../../vendor/wire-elements/pro/resources/css/tailwind/insert-component.css";

### resources/views/
- Just providing the starting directory since everyone's template can be in a different location. Open your template file (guest.blade.php or app.blade.php, etc) and put this in between the <head> tags:
`@vite(['resources/css/app.css', 'resources/js/app.js'])`

After that, I was able to finally run `npm run build` in my project and so far so good - doing more testing to see if it'll work now lol

**Comment by jamesautodude** [comment]
Alright I give up :/ I can't fix all these missing dependencies. After all the above, I now get:

`vendor/wire-elements/pro/resources/css/tailwind/spotlight-component.css:2:5: The `relative` class does not exist. If `relative` is a custom class, make sure it is defined within a `@layer` directive.`

I guess I'll have to find an alternative to modals :/

**Comment by jamesautodude** [comment]
So that all got it working finally in my project, but, upon clicking a button like:

```
<button type="button" class="btn btn-warning" wire:click="$dispatch('openModal', { component: 'Role2.litters.edit-litter', { litter: {{ $litter->id }} } })">
Edit
</button
```

I get this error:
```
Alpine Expression Error: Unexpected token '{'

Expression: "$wire.$dispatch('openModal', { component: 'Role2.litters.edit-litter', { litter: 109 } })"
```

**Comment by jamesautodude** [comment]
Alright so all of the above got it to work... now I'm onto figuring out how to open modals lol

Thank you
