### ISSUE TITLE
Dynamic Sizing

### ISSUE THREAD

**Issue by mauricekindermann** [wire-elements/modal#472]
I have several cases where I need to be able to change the modal size based on what I am loading into it.

For instance a modal might fetch a login screen which is small, or a PDF printing preview, which is full page.

Right now there is no clean way to do this, you can only set a size in the config and that is used everywhere. 

But really - the size of a component should be part of the design markup, not a hard coded config. I can probably figure out how to do it by publishing the views and hacking some if statements, but there must be lots of use cases where your modal changes size?

**Comment by PhiloNL** [comment]
You can, for example:

```blade
<button onclick="Livewire.dispatch('openModal', { component: 'edit-user', modalAttributes: { maxWidth: '7xl' } })">Edit User</button>
```
