### ISSUE TITLE
Error Uncaught Snapshot missing on Livewire component with id

### ISSUE THREAD

**Issue by exonos** [wire-elements/modal#473]
Hi, I will raise this error by this means but in reality the problem is in the modal of the wire elements pro package, I did not find any place for support in the pro package, I have the problem with this livewire error `Uncaught Snapshot missing on Livewire component with id: YVTGfSlUuUnLbYbvcx7Y` that only happens within the pro modal or the slideover, the component simply stops working, its html content is displayed but the error appears in the console and alpine does not push the requests to the methods of the php component.

It is important to mention that this error must necessarily be in the wire elements component because when using the component in another place other than the modal, when accessing it through a route for example, everything works.

**Comment by PhiloNL** [comment]
Hi @exonos 

Thanks for your support! 😄

This error often occurs when you have an unclosed element in one or more components. It could be an unclosed </div> for example.

If the issue still persist, please create a simple repository that replicates this issue and send it to support@wire-elements.dev so I can take a look 🙏🏻😄
