### ISSUE TITLE
Escape key when modal not opened

### ISSUE THREAD

**Issue by XternalSoft** [wire-elements/modal#474]
Hello,

If I hit escape key after installing this package, I get this error

```
livewire.js?id=cc800bf4:1125 Alpine Expression Error: Cannot read properties of undefined (reading 'name')

Expression: "closeModalOnEscape()"
```

I don't know if this can be enough of a fix but in the published template I added a condition before closeModalOnEscape()
``` 
   x-on:keydown.escape.window="show && closeModalOnEscape()"
```

**Comment by connors511** [comment]
This issue was introduced in 2.0.11. Pinning the version to 2.0.10 makes the error go away for me.

**Comment by PhiloNL** [comment]
Thanks for reporting, pushed and tagged release https://github.com/wire-elements/modal/releases/tag/2.0.12
