### ISSUE TITLE
Customize modals

### ISSUE THREAD

**Issue by ju5t** [wire-elements/modal#56]
We have some modals that I'd like to convert to Livewire; but I'm struggling to get things positioned and responsive.

Edit: this is already discussed #26:

<s>The modal disappears when the window is ~680px. It returns on ~640px. This is weird, as it's using Tailwind and the breakpoints are at 640 and 768 by default. We use the default breakpoints in our app. How can we solve this?</s>

Some of our modals are positioned at the top. Often because it has a cleaner look in our app, especially on smaller screens. I am not sure what would be the best approach would be to deal with this, as this very much depends on the design choices of who builds the website, but I would like some more flexibility, if possible.

What do you think?

**Comment by PhiloNL** [comment]
Should be fixed (https://github.com/wire-elements/modal/commit/6fb05c39ce89abc96ab1eb51d47aaa5f9c88d067). You can always publish your views and make modifications to meet your needs.

**Comment by ju5t** [comment]
Ohh! Awesome, I'll give it a shot! Thanks @PhiloNL and @roni-estein!
