### ISSUE TITLE
Opening modal from blade component

### ISSUE THREAD

**Issue by thetwopct** [wire-elements/modal#60]
Hey, thanks for making such a great package. Super simple to use.

I have setup a button to trigger a modal, passing a value from the page I am on:

```
<button 
class="bg-blue-500 text-white p-4"
onclick='Livewire.emit("openModal", "create-document", {{ json_encode(["setComponent" => $component->id]) }})'>
Upload Document
</button>
```

This works perfectly, passes the data I want. Great! 

We are using blade components on the site to keep the styling of every button the same. So I use:

```
<x-button
type="button"
name="Add New Document"
color="primary"
onclick="Livewire.emit('openModal', 'create-document')">
Add a new document</x-button>
```

This also works! But, when I try to pass a value, it breaks. I've tried (what I feel like) all sorts of different quote combinations as i saw your `(notice the single quotes)` comment in docs.

```
<x-button
type="button"
name="Add New Document"
color="primary"
onclick='Livewire.emit("openModal", "create-document", {{ json_encode(["setComponent" => $component->id ]) }})'>
Add a new document</x-button>
```

```
<x-button
type="button"
name="Add New Document"
color="primary"
onclick="Livewire.emit('openModal', 'create-document', {{ json_encode(['setComponent' => $component->id ]) }}
)">
Add a new document</x-button>
```

Am I missing something really obvious?

Using version 1.0.0

Thank you!

**Comment by ju5t** [comment]
I might not be the best person to help you get this sorted out, but I'm not seeing either an error message or an explanation what's going wrong, so right now, it's pretty difficult to help :)

**Comment by designvoid** [comment]
Hi there - I have run into the same issue - following the exact example in the readme trying to pass a model ID to the modal and it throws the following error:
```
Cannot assign int to property App\Http\Livewire\EditUser::$user of type App\Models\User (View: /Users/***/Server/Code/***/vendor/livewire-ui/modal/resources/views/modal.blade.php)
```

(*** just hiding personal details)

**Comment by PhiloNL** [comment]
@designvoid change your property from:
`public User $user;` to `public int|User $user;`

**Comment by nocodelab** [comment]
Ran into the same issue. The docs should be updated accordingly @PhiloNL :) .

**Comment by ju5t** [comment]
I thought Livewire itself didn't have this issue? Correct me if I'm wrong though!

**Comment by boonstoppel** [comment]
I can't get this to work. The passed in arguments are always empty (even tho I can see in the code that the ID is passed via the JS function onclick="Livewire.emit('openModal', 'create-document', {'id': xxxx})">

**Comment by mokhosh** [comment]
@PhiloNL thanks for the great component. This one issue is weird tho.

**Comment by mokhosh** [comment]
😕

**Comment by PhiloNL** [comment]
Sorry, thought the issue was fixed 😅

**Comment by PhiloNL** [comment]
Have you tried using the `@json` directive?

**Comment by mokhosh** [comment]
Yup both json and the new js directive. Same story.

**Comment by PhiloNL** [comment]
How about moving the encoding inside the button component? Not sure if this makes a difference but worth a try.

```

<x-button
type="button"
name="Add New Document"
color="primary"
modal="create-document"
:modal-data=”["setComponent" => $component->id ])”>
Add a new document</x-button>
```

**Comment by mokhosh** [comment]
Tried it. Didn't help.

I don't think the problem is in how we send the data, that part is fine. The problem is in where and how we resolve the model. We need to resolve the model sooner so the "int" turns into a "Model" before we try to assign the data to the property.

**Comment by mpskovvang** [comment]
I have the same experience using Livewire 2.7.2 and Alpine.js 3.6.1.

My workaround:

```PHP
class EditUserModal extends ModalComponent
{
    public User|int $user;

    public function mount(User|int $user)
    {
        $this->user = $user instanceof User ? $user : User::find($user);
    }
}
```

```HTML
<button wire:click.prevent='$emit("openModal", "edit-user-modal", @json(['user' => $user->id]))'>Edit</button>
```

**Comment by dambridge** [comment]
Same issue here, but the fix @mpskovvang still doesn't work for me.
